spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: bidService
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/bidService
    username: admin
    password: Lbcrjntrf12!
